[package]
name = "easy-install"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "easy-install"
repository = "https://github.com/ahaoboy/easy-install"
homepage = "https://github.com/ahaoboy/easy-install"
authors = ["ahaoboy"]


[dependencies]
clap = { version = "4.5", features = ["derive"] }
cargo-binstall = "1.10"
binstalk = "0.28"
binstalk-registry = "0.11"
binstalk-downloader = "0.13"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3.5"
tokio = { version = "1.35", features = [
  "rt",
  "sync",
], default-features = false }
tracing = "0.1"
url = "2.5"
dirs = "5.0"
atomic-file-install = "1.0"
reqwest = { version = "0.12", features = ["json"] }
regex = "1.11"
binstalk-git-repo-api = "0.5.6"
zeroize = "1.8"
compact_str = "0.8"
detect-targets = "0.1"
tracing-subscriber = "0.3"

[[bin]]
name = "ei"
path = "src/main.rs"
