[package]
name = "easy-install"
version = "1.3.0"
edition = "2021"
license = "MIT"
description = "easy-install"
repository = "https://github.com/easy-install/easy-install"
homepage = "https://github.com/easy-install/easy-install"
authors = ["ahaoboy"]

[dependencies]
clap = { version = "^4.5", features = ["derive"] }
# cargo-binstall = "^1.10"
binstalk = "^0.28"
binstalk-registry = "^0.11"
binstalk-downloader = "^0.13"
semver = { version = "^1", features = ["serde"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
tempfile = "^3.15"
tokio = { version = "^1.43", features = [
  "rt",
  "sync",
], default-features = false }
tracing = "^0.1"
url = "^2.5"
dirs = "^6.0"
atomic-file-install = "^1.0"
reqwest = { version = "^0.12", features = ["json"] }
regex = "^1.11"
binstalk-git-repo-api = "^0.5"
zeroize = "^1.8"
compact_str = "^0.8"
detect-targets = "^0.1"
tracing-subscriber = "^0.3"
cargo-dist-schema = "^0.28"
path-clean = "^1.0"
which-shell = "^0.1"
crud-path = "^0.1"
is-admin = "^0.1"
[target.'cfg(not(target_os = "windows"))'.dependencies]
libc = "^0.2"
openssl = { version = "^0.10", features = ["vendored"] }

[profile.release]
codegen-units = 1
lto = true
