name: Test

permissions:
  contents: write

on: [push]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        os: [
            ubuntu-latest,
            windows-latest,
            # macos-latest,
            # macos-13,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo test
        env:
          LOG_LEVEL: TRACE
        run: |
          cargo test

      - name: cargo run
        env:
          LOG_LEVEL: TRACE
        run: |
          echo $PATH
          cargo run -- https://github.com/ahaoboy/mujs-build/releases/tag/v0.0.1
          cargo run -- https://github.com/ahaoboy/neofetch/releases/tag/v0.1.4
          cargo run -- https://github.com/axodotdev/cargo-dist
          echo $PATH

      - name: install on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo run -- https://github.com/ahaoboy/jsc-build

      - name: add path
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "PATH=$env:PATH;C:\Users\runneradmin\easy-install" >> $env:GITHUB_ENV

      - name: test which
        run: |
          which mujs
          which neofetch
          which dist

      - name: test which on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          which jsc