name: Test

permissions:
  contents: write

on: [push]

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  rust-test:
    strategy:
      matrix:
        os: [
            ubuntu-24.04,
            windows-latest,
            # macos-latest,
            # macos-13,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: cargo test
        # env:
        #   LOG_LEVEL: TRACE
        run: |
          cargo test

      - name: cargo run
        # env:
        #   LOG_LEVEL: TRACE
        run: |
          echo $PATH
          cargo run -- https://github.com/ahaoboy/mujs-build
          cargo run -- https://github.com/ahaoboy/neofetch
          cargo run -- https://github.com/axodotdev/cargo-dist
          cargo run -- https://github.com/denoland/deno
          cargo run -- https://github.com/ahaoboy/ffmpeg-build-test/releases/download/v0.0.4/dist-manifest.json
          echo $PATH

      - name: install on ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          cargo run -- https://github.com/ahaoboy/jsc-build
          cargo run -- https://github.com/ahaoboy/spidermonkey-build
          cargo run -- https://github.com/ahaoboy/v8-build

      - name: add path
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          echo "PATH=$env:PATH;C:\Users\runneradmin\easy-install" >> $env:GITHUB_ENV

      - name: test which on windows
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          get-command mujs
          get-command neofetch
          get-command dist
          get-command deno
          get-command ffmpeg

      - name: test which on ubuntu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          which jsc
          which js
          which d8
          which deno
          which denort

          ls -lh  /usr/local/bin
          # ls -lh /usr/local/bin/ffmpeg
          # which ffmpeg

          echo "typeof globalThis.print>'u'&&(globalThis.print=console.log);print(2);" >> test.js
          d8 ./test.js
          js ./test.js
          jsc ./test.js